apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: yaserahmadi/posts
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv # چون برای این پاد یک نود پورت ایجاد کردیم اسم این را تغییر دادیم
spec:
  type: ClusterIP #  اختیاری هست چون بصورت پیش فرض این مقدار را دارد
  selector:
    app: posts # مقدار برچسب پاد را میگیرد
  ports:
  - name: posts
    protocol: TCP
    port: 5000
    targetPort: 5000
