apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
      - name: query
        image: yaserahmadi/query #اگر بخواهیم از داکر هاب بگیرد
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  type: ClusterIP #  اختیاری هست چون بصورت پیش فرض این مقدار را دارد
  selector:
    app: query # مقدار برچسب پاد را میگیرد
  ports:
  - name: query
    protocol: TCP
    port: 5002
    targetPort: 5002
